#GET http://localhost:5000/info 
#GET http://localhost:5000
#GET http://localhost:5000/i

GET http://localhost:5000/api/persons
#GET http://localhost:5000/api/persons/3
#GET http://localhost:5000/info 
#GET http://safe-headland-53320.herokuapp.com/info